In [33]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt
import tensorflow as tf
from time import time

In [34]:
data = pd.read_csv('C:\\Users\\WINSOME\\kyphosis.csv')

In [35]:
data.head()

Kyphosis  Age  Number  Start
0   absent   71       3      5
1   absent  158       3     14
2  present  128       4      5
3   absent    2       5      1
4   absent    1       4     15

In [36]:
from keras.models import Sequential
from keras.layers import Dense

In [37]:
data.columns

Index(['Kyphosis', 'Age', 'Number', 'Start'], dtype='object')

In [38]:
X = data[['Age', 'Number', 'Start']]

In [39]:
y =data ['Kyphosis']

In [40]:
from sklearn.preprocessing import LabelEncoder 

In [41]:
le = LabelEncoder()
y= le.fit_transform(y)

In [42]:
y

array([0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0])

In [43]:
!pip install sklearn

In [44]:
from sklearn.model_selection import train_test_split

In [45]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=101)

In [46]:
model =Sequential()

In [47]:
model.add(Dense(4,input_dim = 3,activation = 'relu'))

In [48]:
model.add(Dense( 3, activation = 'relu'))

In [49]:
model.add(Dense(1, activation = 'sigmoid'))

In [50]:
model.compile(loss = 'binary_crossentropy', optimizer ='adam',metrics =['accuracy'])

In [51]:
model.fit(X_train,y_train, epochs =150, batch_size =10)

Epoch 1/150
64/64 [==============================] - 0s 4ms/step - loss: 9.1163 - accuracy: 0.1875
Epoch 2/150
64/64 [==============================] - 0s 423us/step - loss: 7.3537 - accuracy: 0.1875
Epoch 3/150
64/64 [==============================] - 0s 317us/step - loss: 5.6386 - accuracy: 0.1875
Epoch 4/150
64/64 [==============================] - 0s 467us/step - loss: 3.9614 - accuracy: 0.1875
Epoch 5/150
64/64 [==============================] - 0s 412us/step - loss: 2.9172 - accuracy: 0.1875
Epoch 6/150
64/64 [==============================] - 0s 271us/step - loss: 2.2536 - accuracy: 0.1875
Epoch 7/150
64/64 [==============================] - 0s 235us/step - loss: 1.7204 - accuracy: 0.1875
Epoch 8/150
64/64 [==============================] - 0s 358us/step - loss: 1.3345 - accuracy: 0.2031
Epoch 9/150
64/64 [==============================] - 0s 255us/step - loss: 1.1204 - accuracy: 0.5312
Epoch 10/150
64/64 [==============================] - 0s 259us/step - loss: 1.0211 - accuracy

In [52]:
_,accuracy = model.evaluate(X_test,y_test)

17/17 [==============================] - 0s 3ms/step


In [53]:
print(f"Accuracy : {accuracy*100}")

Accuracy : 70.58823704719543


In [54]:
from sklearn.linear_model import LogisticRegression

In [55]:
logmodel = LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [56]:
logmodel.fit(X_train,y_train)

LogisticRegression(multi_class='ovr', n_jobs=1, solver='liblinear')

In [57]:
predictions=logmodel.predict(X_test)
predictions

array([0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [58]:
y_test

array([0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0])

In [59]:
from sklearn.metrics import classification_report

In [60]:
print(classification_report(y_test,predictions))

              precision    recall  f1-score   support

           0       0.75      1.00      0.86        12
           1       1.00      0.20      0.33         5

    accuracy                           0.76        17
   macro avg       0.88      0.60      0.60        17
weighted avg       0.82      0.76      0.70        17

